CREATE TABLE returns (
    RETURN_ID bigint PRIMARY KEY,
    BORROW_ID bigint,
    RETURN_DATE date,
    LATE_FEE decimal(18, 2),
    FOREIGN KEY (BORROW_ID) REFERENCES borrows(BORROW_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CREATED_AT DATETIME,
    UPDATED_AT DATETIME
);